### PR TITLE
Add step exection time

### PR DESCRIPTION
**Pull request by johannesengl**
This PR add new attribute readers on step object.

After executing a step `execution_finished_at`, `execution_started_at` and `execution_duration`
will be set and can be accessed via attribute readers.

### CODE REVIEW

**Review by nsommer — APPROVED** [review]
Very cool idea! 👍

**Comment by getand** [comment]
I think I would find it more elegant if you could encapsulate it in something like:

```ruby
    def track_execution_time(&block)
      set_execution_started_at
      block.call
    ensure
      set_execution_finished_at
      set_execution_duration
    end
```

and then execute would look like this:

```ruby 
def execute(**changeset)
      track_execution_time do
        mapper = options_mapper || default_options_mapper
        mapper_args = [changeset, self].take(mapper.arity)
        self.mapped_options = mapper.call(*mapper_args)

        guard_args = [changeset, self]

        if_guard_args = guard_args.take(if_guard.arity)
        unless_guard_guard_args = guard_args.take(unless_guard.arity)

        if !instrumentalize_callable(unless_guard, unless_guard_guard_args) && instrumentalize_callable(if_guard, if_guard_args)
          constructor_args = [self, changeset]
          constructor_args = constructor_args.take(constructor.arity)
          self.result = instrumentalize_callable(constructor, constructor_args)
        end

        set_status
        result
      end
    rescue StandardError => e
      self.status = :failed
      self.error = e
      raise
    end
```

**Comment by getand** [comment]
Maybe also merge this one first: https://github.com/nxt-insurance/nxt_pipeline/pull/43

**Comment by johannesengl** [comment]
> I think I would find it more elegant if you could encapsulate it in something like:
> 
> ```ruby
>     def track_execution_time(&block)
>       set_execution_started_at
>       block.call
>     ensure
>       set_execution_finished_at
>       set_execution_duration
>     end
> ```
> 
> and then execute would look like this:
> 
> ```ruby
> def execute(**changeset)
>       track_execution_time do
>         mapper = options_mapper || default_options_mapper
>         mapper_args = [changeset, self].take(mapper.arity)
>         self.mapped_options = mapper.call(*mapper_args)
> 
>         guard_args = [changeset, self]
> 
>         if_guard_args = guard_args.take(if_guard.arity)
>         unless_guard_guard_args = guard_args.take(unless_guard.arity)
> 
>         if !instrumentalize_callable(unless_guard, unless_guard_guard_args) && instrumentalize_callable(if_guard, if_guard_args)
>           constructor_args = [self, changeset]
>           constructor_args = constructor_args.take(constructor.arity)
>           self.result = instrumentalize_callable(constructor, constructor_args)
>         end
> 
>         set_status
>         result
>       end
>     rescue StandardError => e
>       self.status = :failed
>       self.error = e
>       raise
>     end
> ```
> 
> This way you don't pollute the execution with these setters all over the place

Yes that looks better :)

**Comment by johannesengl** [comment]
> ybe also merge this one

Just approved #43

**Review by getand — APPROVED** [review]

**Pull request merged**
